### ISSUE TITLE
Non styled searchable Docs

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io-website#27]
# Requirements:

## Setup a elasticsearch endpoint on aws

* Ensure it has a password

## Upload all file content into elasticsearch with the following structure:

```json
{
   "title": "<string>", 
   "content": "<markdown>",
   "path": "<relative-url>"
}
```

Where title > content in weight

## Upload structure id:

```bash
http://<elasticsearchurl>/deepstream/level1_level2_level3
```
```bash
http://<elasticsearchurl>/deepstream/docs_server_command-line-interface/
```

## Search Result:

- Only return title and path

- Sorted in order of: Title / Best Match -> Content / Best Match

Example, for the search Events

```yaml
pages:
  - Event Emitter
  - Event
content:
  - constants
  - transforming outgoing data
  - value permission
```
